server:
  port: 8080

logging:
  level:
    com.chaltteok.chaltteok: debug

spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=chaltteok&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      schema-locations: classpath:init-schema.sql
      mode: always

social:
  client:
#    kakao:
#      rest-api-key: c23206b22df9ce1d40d85f2aaa021980
#      secret-key:
#      redirect-uri: http://127.0.0.1:8080/kakao-login
#      grant_type: authorization_code

    naver:
      rest-api-key: Fu0jy9r1JgUxld5djIaM
      secret-key: 4EoJ1dQ_DA
      redirect-uri: http://localhost:8080/naver-login
      grant_type: authorization_code

#    google:
#      rest-api-key:
#      secret-key:
#      redirect-uri: http://localhost:8080/google-login
#      grant_type: authorization_code