spring:
  application:
    name: ChalDuok
  datasource:
    url: jdbc:postgresql://localhost:5432/chalduok
    username: postgres
    password: oper-2018
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: false
